// Code generated by "stringer -type SleepState"; DO NOT EDIT.

package device

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Awake-0]
	_ = x[Cleared-1]
	_ = x[Blanked-2]
}

const _SleepState_name = "awakeclearedblanked"

var _SleepState_index = [...]uint8{0, 5, 12, 19}

func (i SleepState) String() string {
	if i < 0 || i >= SleepState(len(_SleepState_index)-1) {
		return "SleepState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SleepState_name[_SleepState_index[i]:_SleepState_index[i+1]]
}
